name: CI DevOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Vérifier Python
      run: python3 --version

    - name: Build Docker image
      run: docker build -t devops-ai-app .

    
    - name: Lancer le conteneur
	run: docker run -d -p 5000:5000 devops-ai-app


  - name: Vérifier que le conteneur tourne
  run: docker ps


  - name: Vérifier logs du conteneur
  run: docker logs $(docker ps -q)  
